### ISSUE TITLE
Add Public Site URI to navigation template

### ISSUE THREAD

**Issue by chris007mi6** [userfrosting/pastries#1]
I just installed the pastries sprinkle to learn more about UserFrosting.
I use a XAMPP develop environment and installed UserFrosting in a subdirectory of the web root directory.

When you click on "List of pastries" in the menu, it links to web root directory and not to the public site uri.

I changed line 7 in /template/navigation/sidebar-menu.html.twig from:

`<a href="/pastries"><i class="fa fa-cutlery fa-fw"></i> <span>{{translate('PASTRIES.LIST')}}</span></a>`

to:

`<a href="{{site.uri.public}}/pastries"><i class="fa fa-cutlery fa-fw"></i> <span>{{translate('PASTRIES.LIST')}}</span></a>`

Thanks,
Chris

**Comment by lcharette** [comment]
Good find. Can you submit a PR ?

**Comment by chris007mi6** [comment]
Yep, I have submitted a PR. I'm new to the whole GIT thing, so I hope it's all ok with the PR :-)
Thanks,
Chris

**Comment by lcharette** [comment]
Merged #2. Thanks !
